name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no $VM_USER@$VM_HOST << EOF
            mkdir -p ~/simple-backend-api
            rm -rf ~/simple-backend-api/*
            exit
          EOF
          scp -i private_key -o StrictHostKeyChecking=no -r ./* $VM_USER@$VM_HOST:~/simple-backend-api
          ssh -i private_key -o StrictHostKeyChecking=no $VM_USER@$VM_HOST << EOF
            cd ~/simple-backend-api
            npm install
            pkill -f node || true
            nohup npm start &
            exit
          EOF
